const categoryTypes = {
    TASKS_REQUEST: "TASKS_REQUEST",
    TASKS_SUCCESS: "TASKS_SUCCESS",
    TASKS_FAILURE: "TASKS_FAILURE",

    ADD_TASK_REQUEST: "ADD_TASK_REQUEST",
    ADD_TASK_SUCCESS: "ADD_TASK_SUCCESS",
    ADD_TASK_FAILURE: "ADD_TASK_FAILURE",

    EDIT_TASK_REQUEST: "EDIT_TASK_REQUEST",
    EDIT_TASK_SUCCESS: "EDIT_TASK_SUCCESS",
    EDIT_TASK_FAILURE: "EDIT_TASK_FAILURE",
}

export default categoryTypes;
